AWSTemplateFormatVersion: "2010-09-09"
Description: 나눔장 프로젝트 DynamoDB 테이블

Resources:
  CoBuyingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CoBuyingTable
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: AttendeeId
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
        - AttributeName: AttendeeId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  CoBuyingTableName:
    Description: "DynamoDB 테이블 이름"
    Value: !Ref CoBuyingTable
  CoBuyingTableArn:
    Description: "DynamoDB 테이블 ARN"
    Value: !GetAtt CoBuyingTable.Arn
